Repository k3s-io/k3s, pull requests merged in 2020-07, with the labels that each got.

#1768 Configure default signer implementation to use ClientCA instead of ServerCA
  pkg/daemons/control/server.go
Labels: [zube]: Next Up

#2042 Update coredns version for master
  manifests/coredns.yaml
  pkg/deploy/zz_generated_bindata.go
  scripts/airgap/image-list.txt
Labels: [zube]: Peer Review

#2041 Update coredns version for 1.18
  manifests/coredns.yaml
  pkg/deploy/zz_generated_bindata.go
  scripts/airgap/image-list.txt
Labels: [zube]: Peer Review

#2040 Update coredns version for 1.17
  manifests/coredns.yaml
  pkg/deploy/zz_generated_bindata.go
  scripts/airgap/image-list.txt
Labels: [zube]: Peer Review

#2056 Always validate K3S_URL if running agent.
  install.sh
Labels: [zube]: To Verify
