Repository k3s-io/k3s, pull requests merged in 2021-06, with the labels that each got.

#3405 add log message indicating etcd snapshots are disabled
  pkg/cli/server/server.go
Labels: EtcdBackupRestoreEnhancements, kind/enhancement

#3413 fix possible race where bootstrap data might not save
  pkg/cluster/cluster.go
Labels: EtcdBackupRestoreEnhancements, kind/bug

#3354 [ Backport 1.21 ] - etcd subcommands 1.21
  cmd/etcdsnapshot/main.go
  cmd/k3s/main.go
  cmd/server/main.go
  main.go
  pkg/cli/cmds/etcd_snapshot.go
  pkg/cli/cmds/server.go
  pkg/etcd/etcd.go
Labels: EtcdBackupRestoreEnhancements

#3436 Add events to deploy controller
  pkg/deploy/controller.go
  pkg/server/server.go
Labels: kind/enhancement

#3430 Send systemd notifications for both server and agent
  pkg/agent/run.go
  pkg/cli/server/server.go
Labels: kind/enhancement

#3452 Change containerd image leases from 24h to permanent
  pkg/agent/containerd/containerd.go
Labels: kind/enhancement

#3494 Add Unit Test Coverage to CI
  .github/.codecov.yml
  .github/workflows/unitcoverage.yaml
  scripts/validate
Labels: kind/feature
